name: Build and Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: '6.3.x'

      - name: Determine Version
        id: version_step # step id used as a reference for output values
        uses: gittools/actions/gitversion/execute@v3.2.1
        with:
          useConfigFile: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        # with:
        #   version: 10
          # run_install: false

      - name: Print Env Variables
        run: |
         printenv | sort

      - name: Bump version and push tag
        run: |
          #  npm version patch -m "Release %s [skip ci]"
          #  git push --follow-tags
          sed -i 's/"version": *"[^"]*"/"version": "${{ env.GitVersion.FullSemVer }}"/' package.json
      - name: Show version
        run: |
          echo "Version: ${{ steps.version_step.outputs.full_sem_ver }}"
          echo "GitVersion: ${{ env.GitVersion.FullSemVer }}"
          cat package.json

      - name: Install dependencies
        run: pnpm install

      # - name: Run tests
      #   run: npm test

      - name: Build package
        run: pnpm run build

      # - name: Publish to npm
      #   run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
